dist: focal
language: node_js
node_js:
  - "lts/*"
  - node
services:
  - docker
  - postgresql
before_install:
  - docker build -t forethought .
  - docker run -d -p 8080:8080 forethought
  - docker ps -a
